export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_READY = 'LOAD_USERS_READY';

export const FETCH_NEXT_CLICKED = 'FETCH_NEXT_CLICKED';
export const FETCH_PREVIOUS_CLICKED = 'FETCH_PREVIOUS_CLICKED';
